version: "3.5"

services:
        # サービス名(folder名)
        rails_back:
                build:
                        context: ./rails_back
                        dockerfile: ./Dockerfile
                command: bundle exec rails server -p 8000 -b 0.0.0.0
                ports:
                        - "8000:8000"
                depends_on:
                        - mysql_db
                volumes:
                        - ./rails_back:/rails_back
                environment:
                        MYSQL_USERNAME: ${MYSQL_USERNAME}
                        MYSQL_DATABASE : ${MYSQL_DATABASE}
                        MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
                        MYSQL_HOST : ${MYSQL_HOST}
                container_name: sin_records_api

        # # サービス名(folder名)
        mysql_db:
                build:
                        context: ./mysql_db
                        dockerfile: ./Dockerfile
                volumes: 
                        - ./mysql_db:/var/run/mysqld
                # image: mysql:5.7
                command: --innodb_use_native_aio=0
                environment:
                        MYSQL_DATABASE: ${MYSQL_DATABASE}
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                ports:
                        - "3306:3306"
                        
        # サービス名(folder名)
        vue_front:
                stdin_open: true
                build: 
                        context: ./vue_front
                        dockerfile: ./Dockerfile
                command:  yarn dev
                ports:
                        - "5173:5173"
                volumes:
                        - /vue_front/node_modules
                        - ./vue_front:/vue_front
                container_name: sin_records_web

        # サービス名(folder名)
        nginx_proxy:
                build:
                        context: ./nginx_proxy
                        dockerfile: ./Dockerfile
                ports:
                        - "80:80"
                volumes:
                        - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf  
                depends_on:
                        - vue_front
                        - rails_back
